Code/MvcAppDCR/Controllers/SucursalUsuarioController.cs
using Business;
using Controllers;
using Domine;
using MvcAppDCR.Code;
using MvcAppDCR.Code.Business.Security;
using MvcAppDCR.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Controllers
{
    public class SucursalUsuarioController : BaseController
    {
        public ActionResult AssignSucursal(int idUsuario)
        {
            Usuario user = UsuarioBusiness.Instance.GetEntity(idUsuario);

            ViewBag.SucursalOperaciones = new BSecurity().GetSucursalOperacionModels(user);

            return View(user);
        }
                
            [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AssignSucursal(string sucursales, Usuario user)
        {
            try
            {
                var listSucursales = new JavaScriptSerializer().Deserialize<List<Sucursal>>(sucursales);
                
                SucursalBusiness.Instance.CreateSucursalUsuario(user, listSucursales);

                return Json(new { success = true, url = "Usuario/Index" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { result = new { }, count = 0, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

            [HttpPost]
            public JsonResult GetUsuarioSucursal()
            {
                try
                {
                    var list = SucursalUsuarioBusiness.Instance.GetUsuarioSucursal()
                                        .Select(p => p.Sucursal);

                    var options = WebHelper.GetSelectListItem(list, "IdSucursal", "Descripcion");

                    return Json(new { status = Constant.SuccessMessages.MESSAGE_OK, Options = options });
                }
                catch (Exception ex)
                {
                    return ExceptionManager.Instance.JsonError(ex);
                }
            }
    }
}

Code/MvcAppDCR/Controllers/UsuarioController.cs
using Business;
using CurrentContext;
using Enumerations;
using Domine;
using MvcAppDCR.Code;
using MvcAppDCR.Code.Business.Security;
using MvcAppDCR.Model;
using MvcAppDCR.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Controllers
{
    public class UsuarioController : BaseController
    {
        private readonly BSecurity Business = new BSecurity();

        public ActionResult Index()
        {
            ViewBag.Perfiles = WebHelper.GetSelectListItem(PerfilBusiness.Instance.GetAllActives(), "IdPerfil", "Nombre", true);

            return View();
        }

        public JsonResult GetUsuarios(string nombre = "", string apellido = "", string nombreUsuario = "", long idPerfil = 0, [Bind(Prefix = "$top")]int top = 10, [Bind(Prefix = "$skip")]int skip = 0)
        {
            try
            {
                int rowCount = 0;

                var list = UsuarioBusiness.Instance.GetByFilters(nombre, apellido, nombreUsuario, idPerfil, skip, top, ref rowCount);

                return this.JsonSerialize(new { status = Constant.SuccessMessages.MESSAGE_OK, result = list, count = rowCount }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { result = new { }, count = 0, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult ABMUsuario(long? id)
        {
            var empresas = EmpresaBusiness.Instance.GetAllEmpresas();

            ViewBag.Perfiles = new BSecurity().GetPerfilModel(id);

            ViewBag.Empresas = WebHelper.GetSelectListItem(empresas, "Id", "Nombre");

            if (!id.HasValue)
            {
                return View(Business.GetUsuarioModel(id));
            }

            UsuarioModel usuario = Business.GetUsuarioModel(id);

            if (usuario == null)
            {
                return HttpNotFound();
            }

            return View(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ABMUsuario(UsuarioModel usuario, string perfiles, string vendedoresEmpresas, bool changecontrasenia = false)
        {
            try
            {
                if (usuario.UsuarioMod.IdUsuario > 0 && !changecontrasenia)
                {
                    ModelState.Remove("UsuarioMod.Contrasenia");
                }

                if (usuario.UsuarioMod.IdUsuario > 0 && changecontrasenia && usuario.UsuarioMod.Contrasenia == null)
                {
                    return ExceptionManager.Instance.JsonError("Debe ingresar una contraseña");
                }

                if (ModelState.IsValid)
                {
                    var selectedPerfiles = new JavaScriptSerializer().Deserialize<List<Perfil>>(perfiles);

                    Business.SaveOrUpdate(usuario, selectedPerfiles, changecontrasenia);

                    return Json(
                        new
                        {
                            msg = "Registro guardado correctamente",
                            status = Constant.SuccessMessages.MESSAGE_OK,
                            url = Url.Action("Index")
                        });
                }
                else
                {
                    return ExceptionManager.Instance.JsonError(ModelState);
                }
            }
            catch (ValidationException vex)
            {
                return ExceptionManager.Instance.JsonError(vex.Message);
            }
        }

        [HttpPost]
        public JsonResult ChangeContrasenia(string actual = "", string contrasenia = "", string confirmacion = "")
        {
            try
            {
                if (!string.IsNullOrEmpty(contrasenia) || !string.IsNullOrEmpty(actual) || !string.IsNullOrEmpty(confirmacion))
                {
                    if (contrasenia == confirmacion)
                    {
                        if (CustomMembership.ValidateUser(SessionContext.UsuarioActual.NombreUsuario, actual))
                        {
                            UsuarioBusiness.Instance.ChangeContrasenia(contrasenia);

                            return Json(new { status = Constant.SuccessMessages.MESSAGE_OK });
                        }
                        else
                        {
                            return ExceptionManager.Instance.JsonError("La contraseña actual ingresada es incorrecta.");
                        }
                        
                    }
                    else
                    {
                        return ExceptionManager.Instance.JsonError("La contraseña nueva no coincide con la confirmacion.");
                    }                   
                }
                else
                {
                    return ExceptionManager.Instance.JsonError("Debe completar los campos requeridos (*)");
                }
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Delete(long id)
        {
            try
            {
                if (SessionContext.UsuarioActual.IdUsuario != id)
                {
                    UsuarioBusiness.Instance.DeleteLogic(id, null, AuditoriaBusiness.Instance.AuditoriaUsuario);

                    return Json(new { status = Constant.SuccessMessages.MESSAGE_OK });
                }
                else
                {
                    return ExceptionManager.Instance.JsonError("No puede borrar el usuario con el que ha iniciado sesión actualmente");
                }
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }
    }
}

Code/MvcAppDCR/Views/SucursalUsuario/AssignSucursal.cshtml
@model Usuario

@{
    ViewBag.Title = string.Format(Resource.AsingnacionSucursal + " - Usuario: " + Model.NombreUsuario);
}

@section HeadSection{
    @Styles.Render(Constant.Bundle.CSS_SyncfusionAll)
}

@section ScriptSection
{
    @Scripts.Render(Constant.Bundle.Script_SyncfusionAll)

    <script src="@Url.Content("~/Scripts/Site/SucursalUsuario/am.js")"></script>
}

<section class="panel">
    <header class="panel-heading">
        @ViewBag.Title
    </header>
    <div class="panel-body">
        @using (Ajax.BeginForm("AssignSucursal", "SucursalUsuario", null, new AjaxOptions
        {
            HttpMethod = Constant.Ajax.Post,
            InsertionMode = InsertionMode.Replace,
            OnBegin = Constant.Ajax.JsOnBeginAjax,
            OnSuccess = "onSuccessSendAssignSucursal(data)"
        },
        new { @class = "cmxform form-horizontal", id = "form-usuario-sucursales-operacion" }))
        {
            @Html.AntiForgeryToken()     
            @Html.HiddenFor(model => model.IdUsuario)          
            <div class="form">
                <div class="@Bootstrap.formgroup">
                    <div class="col-lg-12">
                        <div class="input-group m-bot15">
                            @(Html.EJ().Grid<Sucursal>("sucursalOperacionGrid")
                                .Datasource((List<MvcAppDCR.Model.Security.SucursalModel>)ViewBag.SucursalOperaciones)
                                .AllowPaging()
                                .PageSettings(page => { page.PageSize(Constant.Grid.PageSize); })
                                .Columns(col =>
                                {
                                    col.Field("IdSucursal").Visible(false).Add();
                                    col.Field("EmpresaNombre").HeaderText("Empresa").Width(90).TextAlign(TextAlign.Center).Add();
                                    col.Field("Nombre").HeaderText("Sucursal").Width(90).TextAlign(TextAlign.Center).Add();
                                    col.Template(true).HeaderText("Permiso")
                                         .TemplateID("#chkTemplate")
                                        .TextAlign(TextAlign.Center).Width(35).Add();
                                }).ClientSideEvents(eve => eve.QueryCellInfo("queryCellInfo"))
                            )
                            @Html.EJ().ScriptManager()
                        </div>
                    </div>
                </div>
                <div class="@Bootstrap.formgroup">
                    <div class="col-lg-offset-3 col-lg-12">
                        <b>
                            <label class="error-label" id="@Constant.SuccessMessages.ERROR_VAR"></label>
                        </b>
                    </div>
                </div>
                <div class="@Bootstrap.formgroup">
                    <div class="col-lg-offset-4 col-lg-12">
                        <button class="btn btn-primary" type="submit" onclick="addSucursal()">@Resource.Save</button>
                        <button class="btn btn-default" type="button" onclick="window.location = '@Url.Action("Index", "Usuario")'">@Resource.Volver</button>
                    </div>
                </div>
            </div>    
            @Html.Hidden("sucursales")
        }
    </div>
</section>
<script type="text/x-jsrender" id="chkTemplate">
    <input type="checkbox" id="{{:IdSucursal}}" data-selected="{{:Selected}}" sucursaloperacion="true" class="row-header" />
</script>