Code/MvcAppDCR/Controllers/CuentaCorrienteController.cs
using Business;
using CrystalDecisions.CrystalReports.Engine;
using CurrentContext;
using Domine;
using Enumerations;
using Mvc.Utils;
using MvcAppDCR.Code;
using MvcAppDCR.Model.Entities;
using MvcAppDCR.Utils;
using Resources;
using System;
using System.Collections.Generic;
using System.Net.Mime;
using System.Web.Mvc;
using System.Linq;
using Luma.Utils.Security;
using Domine.Dto;
using Luma.Utils;

namespace Controllers
{
    public class CuentaCorrienteController : BaseController
    {
        //
        // GET: /CuentaCorriente/

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCuentasCorrientes(string cliente = "", [Bind(Prefix = "$top")]int top = 10, [Bind(Prefix = "$skip")]int skip = 0)
        {
            try
            {
                int rowCount = 0;

                var list = CuentaCorrienteBusiness.Instance.GetCuentaCorrienteList(cliente);

                return this.JsonSerialize(new { status = Constant.SuccessMessages.MESSAGE_OK, result = list, count = rowCount }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { result = new { }, count = 0, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult ABMCuentaCorriente(long? id)
        {
            ViewBag.EstadoCtaCte = DCREnumerationsHelper.GetEstadoCtaCte(insertIndistinct: false);

            if (!id.HasValue || id.Value <= 0)
            {
                return View(new CuentaCorriente());
            }

            var entity = CuentaCorrienteBusiness.Instance.GetEntity(id.Value);

            if (entity == null)
            {
                return HttpNotFound();
            }

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ABMCuentaCorriente(CuentaCorriente cuentaCorriente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CuentaCorrienteBusiness.Instance.SaveOrUpdateCuentaCorriente(cuentaCorriente);

                    return Json(
                        new
                        {
                            msg = "Registro guardado correctamente",
                            status = Constant.SuccessMessages.MESSAGE_OK,
                            url = Url.Action("Index")
                        });
                }
                else
                {
                    return ExceptionManager.Instance.JsonError(ModelState);
                }
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }

        public ActionResult ReporteCuentaCorriente(string fechaDesde, string fechaHasta, int idCuentaCorriente = 0)
        {
            try
            {
                DateTime? fecha_Desde = null;
                DateTime? fecha_Hasta = null;

                if (fechaDesde == null)
                {
                    fecha_Desde = DateTime.Now.AddMonths(-6);
                }
                else
                {
                    fecha_Desde = Convert.ToDateTime(fechaDesde);
                }

                if (fechaHasta == null)
                {
                    fecha_Hasta = DateTime.Now.AddDays(1);
                }
                else
                {
                    fecha_Hasta = Convert.ToDateTime(fechaHasta).AddDays(1);
                }

                decimal debito = 0.0M;
                decimal credito = 0.0M;
                decimal saldo = 0.0M;
                decimal saldoAnterior = 0.0M;

                OperacionCuentaCorriente opcuentaCorrienteBD = new OperacionCuentaCorriente();

                var cuentaCorriente = CuentaCorrienteBusiness.Instance.GetEntity(idCuentaCorriente);

                List<OperacionCuentaCorriente> opBD = OperacionBusiness.Instance.GetByConditions<OperacionCuentaCorriente>(op => op.Fecha >= fecha_Desde && op.Fecha <= fecha_Hasta && op.IdCuentaCorriente == cuentaCorriente.IdCuentaCorriente);

                debito = CuentaCorrienteBusiness.Instance.GetCtaCteSaldoDebito(fecha_Desde, fecha_Hasta, idCuentaCorriente);

                credito = CuentaCorrienteBusiness.Instance.GetCtaCteSaldoCredito(fecha_Desde, fecha_Hasta, idCuentaCorriente);

                saldo = credito - debito;

                saldoAnterior = CuentaCorrienteBusiness.Instance.GetSaldoByFecha(fecha_Desde, idCuentaCorriente);

                if (cuentaCorriente != null)
                {
                    var opcuentaCorrienteModel = new List<OperacionCuentaCorrienteModel>();

                    opcuentaCorrienteModel.Add
                                               (
                                                    new OperacionCuentaCorrienteModel
                                                    {
                                                        IdOperacionCuentaCorriente = 0,
                                                        IdCuentaCorriente = idCuentaCorriente,
                                                        TipoMovimiento = saldoAnterior < 0 ? 1 : 2,
                                                        Descripcion = "Saldo al " + fecha_Desde.Value.AddDays(-1).ToShortDateString(),
                                                        Fecha = fecha_Desde.Value.AddDays(-1),
                                                        Monto = saldoAnterior,
                                                        Estado = 1,
                                                        Debito = saldoAnterior < 0 ? saldoAnterior : 0,
                                                        Credito = saldoAnterior >= 0 ? saldoAnterior : 0,
                                                        Saldo = saldoAnterior
                                                    }
                                               );

                    foreach (var item in opBD)
                    {
                        opcuentaCorrienteBD = OperacionCuentaCorrienteBusiness.Instance.GetEntity(item.IdOperacionCuentaCorriente);

                          if (opcuentaCorrienteBD.TipoMovimiento == 1)
	                      {
	                      	 saldoAnterior = saldoAnterior - opcuentaCorrienteBD.Monto;
	                      }
                          else
	                      {
                             saldoAnterior = saldoAnterior + opcuentaCorrienteBD.Monto;
	                      }

                        opcuentaCorrienteModel.Add
                                                (                                              
                                                     new OperacionCuentaCorrienteModel
                                                     {
                                                        IdOperacionCuentaCorriente = opcuentaCorrienteBD.IdOperacionCuentaCorriente,
                                                        IdCuentaCorriente = opcuentaCorrienteBD.IdCuentaCorriente,
                                                        TipoMovimiento = opcuentaCorrienteBD.TipoMovimiento,
                                                        Descripcion = opcuentaCorrienteBD.Descripcion,
                                                        Fecha = opcuentaCorrienteBD.Fecha,
                                                        Monto = opcuentaCorrienteBD.Monto,
                                                        Estado = opcuentaCorrienteBD.Estado,
                                                        Debito = opcuentaCorrienteBD.TipoMovimiento == 1 ? opcuentaCorrienteBD.Monto : 0,
                                                        Credito = opcuentaCorrienteBD.TipoMovimiento == 2 ? opcuentaCorrienteBD.Monto : 0,
                                                        Saldo = saldoAnterior
                                                     }
                                                );
                        //opcuentaCorrienteModel.Add((OperacionCuentaCorrienteModel)WebHelper.GenericLoad(opcuentaCorrienteBD, new OperacionCuentaCorrienteModel()));
                    }

                    ReportClass reportClass = ReportHelper.LoadReport("CuentaCorrienteReport");

                    //reportClass.SetDataSource(opcuentaCorrienteModel.OrderByDescending(op => op.Fecha));
                    reportClass.SetDataSource(opcuentaCorrienteModel);
                    reportClass.SetParameterValue("nombreCliente", cuentaCorriente.Cliente.Nombre);
                    reportClass.SetParameterValue("numeroCtaCte", cuentaCorriente.IdCuentaCorriente.ToString());
                    reportClass.SetParameterValue("fechaDesde", fechaDesde);
                    reportClass.SetParameterValue("fechaHasta", fechaHasta);
                    reportClass.SetParameterValue("total", saldo);
                    reportClass.SetParameterValue("debito", debito);
                    reportClass.SetParameterValue("credito", credito);

                    return File(ReportHelper.ShowReport(reportClass, ReportFormat.PDF), MediaTypeNames.Application.Pdf);
                }
                else
                {
                    return RedirectToAction("Error", "Access", new { errorType = Resource.Error, message = Resource.CuentaCorrienteNoEncontrada, btnGoToLabel = "", redirectBtn = false });
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Access", new { errorType = Resource.Error, message = ex.Message, btnGoToLabel = "", redirectBtn = false });
            }
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult PagoCliente(PagoClienteModel model)
        {
            if (ModelState.IsValid)
            {
                string msg = "";

Code/MvcAppDCR/Views/CuentaCorriente/ABMCuentaCorriente.cshtml
@model CuentaCorriente

@{
    ViewBag.Title = string.Format(Resource.ABMTitle, Resource.CuentaCorriente);
}

<section class="panel">
    <header class="panel-heading">
        @ViewBag.Title
    </header>
    <div class="panel-body">
        @using (Ajax.BeginForm("ABMCuentaCorriente", null, new AjaxOptions
        {
            HttpMethod = "Post",
            InsertionMode = InsertionMode.Replace,
            OnBegin = Constant.Ajax.JsOnBeginAjax,
            OnSuccess = Constant.Ajax.JsOnSuccessAjax
        },
		new { @class = "cmxform form-horizontal", id = "form-cuentaCorriente", autocomplete = "off" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.IdCuentaCorriente)
            @Html.HiddenFor(model => model.IdCliente)
            <div class="form">
				<div class="@Bootstrap.formgroup">
					@Html.LabelFor(model => model.Estado, new { @class = Bootstrap.label })
					<div class="col-lg-6">
						<div class="input-group m-bot15">
							<span class="input-group-addon">*</span>
							 @Html.DropDownListFor(model => model.Estado, (List<SelectListItem>)ViewBag.EstadoCtaCte, new {@class = Bootstrap.input, Resource.Estado })
						</div>
						@Html.ValidationMessageFor(model => model.Estado)
					</div>
				</div>
				<div class="@Bootstrap.formgroup">
					<div class="col-lg-offset-3 col-lg-6">
						<b>
							<label class="error-label" id="@Constant.SuccessMessages.ERROR_VAR"></label>
						</b>
					</div>
				</div>
                <hr />
                <div class="@Bootstrap.formgroup">
                    <div class="col-lg-offset-3 col-lg-6">
                        <button class="btn btn-primary" type="submit" id="btnSave">@Resource.Save</button>
                        <button class="btn btn-default" type="button" onclick="window.location = '@Url.Action("Index")';">@Resource.Cancel</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Code/MvcAppDCR/Views/CuentaCorriente/Index.cshtml
@{
	ViewBag.Title = "Cuenta Corriente";

    var create = false;
    var edit = true;
    var delete = true;
}

@section HeadSection{
    @Styles.Render(Constant.Bundle.CSS_SyncfusionAll)
}

@section ScriptSection{
    @Scripts.Render(Constant.Bundle.Script_SyncfusionAll)

    <script type="text/javascript" src="@Url.Content("~/Scripts/Site/CuentaCorriente/cuentaCorriente.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/Scripts/Site/Reporte/report.js")"></script>
}

@Html.Partial("_ColumnCommandGridStandar", new ConfigStandarCommand
{
    UrlEdit = (edit ? Url.Action("ABMCuentaCorriente") + "/{{:IdCuentaCorriente}}" : ""),
    ButtonFilter = "btnSearch",
    CustomeTemplate = "<a style=\"float:right\" href=\"" + "javascript:abrirReporte(" + "{{:IdCuentaCorriente}}" + ")\" role=\"button\" class=\"btn btn-info btn-sm\" title=\"" + Resource.ImprimirResumen + "\"><span class=\"fa fa-print\"></span></a>"
})

<div class="panel">
    <div class="panel-heading">
        @ViewBag.Title
        <span class="tools pull-right">
            <a class="fa fa-chevron-down" href="javascript:;"></a>
        </span>
		@if (create)
		{
			<a role="button" class="btn btn-primary btn-primary-new" href="@Url.Action("ABMCuentaCorriente")">
				<span class="fa fa-file-o"></span>
				&nbsp; @Resource.Create Cuenta Corriente
			</a>
		}
    </div>
    <div class="panel-body" style="display: none;">
        <div class="row">
            <div class="@Bootstrap.formgroup col-sm-3">
                @Html.Label("", Resource.Clientes)
                @Html.TextBox("txtNombre", "", new { @id = "txtNombre", @class = Bootstrap.input })
            </div>
        </div>
        <div>
            <button id="btnSearch" type="button" class="btn btn-primary" data-loading-text="@Resource.Searching">
                <span class="fa fa-search"></span>
                &nbsp; @Resource.Search
            </button>
            <button id="btnRestore" type="button" class="btn btn-warning">
                <span class="fa fa-repeat"></span>
                &nbsp; @Resource.Restore
            </button>
        </div>
    </div>
</div>
@Html.Hidden("hiddenIdCtaCte")

@(Html.EJ().Grid<CuentaCorriente>("cuentaCorrienteGrid")
    .Datasource(d => d.URL(Url.Action("GetCuentasCorrientes")))
    .AllowPaging()   
    .PageSettings(page => { page.PageSize(Constant.Grid.PageSize); })
    .Columns(col =>
    {
		col.Field("IdCuentaCorriente").HeaderText("Numero Cuenta").IsPrimaryKey(true).Width(2).Add();
		col.Field("NombreCliente").HeaderText("Cliente").TextAlign(TextAlign.Left).Width(3).Add();
        col.Field("Debito").Format("{0:C2}").HeaderText("Debe").TextAlign(TextAlign.Left).Width(3).Add();
        col.Field("Credito").Format("{0:C2}").HeaderText("Haber").TextAlign(TextAlign.Left).Width(3).Add();
        col.Field("Saldo").Format("{0:C2}").HeaderText("Saldo").TextAlign(TextAlign.Left).Width(3).Add();
        col.HeaderText("")
            .Template(true)
            .TemplateID("#" + Constant.Partial.IDStandarTemplateCommand)
            .TextAlign(TextAlign.Center).Width(2).Add();
    })    
    )
<div id="cuentaCorrienteinfo" 
    data-search-url="@Url.Action("GetCuentasCorrientes")"
    data-report-url="@Url.Action("ReporteCuentaCorriente")"
	data-nombre-reporte="@Resource.ReporteCuentaCorriente">
</div>

<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="modal-reporte" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel" align="center">Resumen Cuenta</h4>
            </div>
            <hidden id="hiddenCaja" value="0"></hidden>
            <div class="modal-body">
                <div id="grid-detalle-edit-popup">
                    @Html.Partial("~/Views/CuentaCorriente/Reporte.cshtml", new ViewDataDictionary { { "PopUp", true } })
                </div>
            </div>
        </div>
    </div>
</div>

Code/MvcAppDCR/Views/CuentaCorriente/PagoCliente.cshtml
@model  MvcAppDCR.Model.Entities.PagoClienteModel
@{
    Layout = null;

}
<div class="panel-body">
    @using (Ajax.BeginForm("PagoCliente", "CuentaCorriente", null, new AjaxOptions
    {
        HttpMethod = Constant.Ajax.Post,
        InsertionMode = InsertionMode.Replace,
        OnBegin = Constant.Ajax.JsOnBeginAjax,
        OnSuccess = "successAjaxPago"
    },
            new { @class = "cmxform form-horizontal", id = "form-perfil" }))
    {
        @Html.AntiForgeryToken()
        <div class="form">
            <div class="@Bootstrap.formgroup">
                @Html.LabelFor(model => model.IdCliente, new { @class = Bootstrap.label })
                <div class="col-lg-8">
                    <div class="input-group m-bot15">
                        <span class="input-group-addon">*</span>
                        @(Html.EJ().Autocomplete("acCliente")
                            .ShowEmptyResultText()
                            .AllowAddNew(false)
                            .Datasource(u => u.URL(Url.Action("AutocompleteClientes", "AutoComplete") + "?take=30&insertarIndistinto=true&"))
                            .AutocompleteFields(f => f.Text("Text").Key("Value"))
                            .EnableAutoFill()
                            .CaseSensitiveSearch(false)
                            .ClientSideEvents(e => e.Select("autocompleteClientSelectEvent").FocusOut("autocompleteClientLostFocustEvent"))
                            .FilterType(FilterOperatorType.Contains)
                            .HighlightSearch()
                            .MultiSelectMode(MultiSelectModeTypes.None)
                            .Width("100%"))
                        @Html.HiddenFor(model => model.IdCliente)
                    </div>
                    @Html.ValidationMessageFor(model => model.IdCliente)
                </div>
            </div>
            <div class="@Bootstrap.formgroup">
            </div>
            <div class="@Bootstrap.formgroup">
                @Html.Label("label-saldo-title", "Saldo: ", new { @class = Bootstrap.label })
                <div class="col-lg-6">
                    <div class="input-group m-bot15">
                        @Html.Label("label-saldo", "$0", new { id = "label-saldo", style = "font-size: x-large;" })
                    </div>

                </div>
            </div>
            <div class="@Bootstrap.formgroup">
                @Html.LabelFor(model => model.Importe, new { @class = Bootstrap.label })
                <div class="col-lg-6">
                    <div class="input-group m-bot15">
                        <span class="input-group-addon">*</span>
                        @Html.TextBoxFor(model => model.Importe, new { @class = "form-control", type = "number" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Importe)
                </div>
            </div>
            <div class="@Bootstrap.formgroup">
                @Html.LabelFor(model => model.Tipo, new { @class = Bootstrap.label })
                <div class="col-lg-6">
                    <div class="input-group m-bot15">
                        <span class="input-group-addon">*</span>
                        @Html.DropDownListFor(model => model.Tipo, ViewBag.Tipo as IEnumerable<SelectListItem>, new { @class = Bootstrap.input })
                    </div>
                    @Html.ValidationMessageFor(model => model.Tipo)
                </div>
            </div>
            <div class="@Bootstrap.formgroup">
                <div class="col-lg-offset-3 col-lg-6">
                    <button class="btn btn-primary" type="submit" onclick="return validateInfo()">@Resource.Save</button>
                    <button class="btn btn-default" type="button" onclick="backCliente(); return false;">@Resource.Cancel</button>
                </div>
            </div>
        </div>
    }
</div>
<script>

    function successAjaxPago(data) {
        hideOverlay();
        if (data.success) {
            backCliente();
            showComprobante(data.id);
        }
        else {
            popupError(null, data.msg);
        }
    }

    function showComprobante(id) {
        $.ajax({
            url: '/CuentaCorriente/PrintComprobante',
            type: "GET",
            dataType: "html",
            data: { idoperacion: encodeURI(id) },
            cache: false,
            success: function (data) {
                var printWindow = window.open('', '', 'height=400,width=800');
                printWindow.document.write(data);
                printWindow.document.close();
                printWindow.print();
                printWindow.close();
            },
            error: function (xhr, status, error) {
                alert(xhr.responseText);
            }
        });

    }

    function validateInfo() {
        if (tmpclient == "") {
            popupError(null, "Complete los campos obligatorios.");
            return false;
        }
        if (saldo < parseFloat($("#Importe").val()) && $("#Tipo").val() == "1") {
            popupError(null, "El importe deber ser menor al saldo");
            return false;
        }

        if (parseFloat($("#Importe").val()) <= 0) {
            popupError(null, "El importe deber ser un número positivo");
            return false;
        }

        return true;
    }
    var saldo = 0;
    var tmpclient = "";

    function autocompleteClientSelectEvent(args) {
        $("#IdCliente").val(args.key);
        tmpclient = args.value;
        getSaldo();
    }

    function autocompleteClientLostFocustEvent(args) {
        if (args.value !== tmpclient) {
            $("#IdCliente").val("");
            $("#acCliente").val("");
            tmpclient = "";
            saldo = 0;
            $("#label-saldo").text("$0");

        }
    }


    function getSaldo() {
        if ($('#IdCliente').val() != "") {
            showOverlay();
            $.ajax({
                url: "/CuentaCorriente/Saldo",
                data: JSON.stringify(
                {
                    idCliente: $('#IdCliente').val()
                }),
                type: 'POST',
                dataType: 'json',
                contentType: 'application/json',
                success: function (data) {
                    hideOverlay();
                    if (data.success) {
                        saldo = parseFloat(data.importe.toFixed(2));
                        $("#label-saldo").text("$" + data.importe.toFixed(2));
                        if (saldo < 0) {
                            $("#label-saldo").css("color", "red");
                        } else {
                            $("#label-saldo").css("color", "#767676");
                        }
                    }
                    else {
                        $("#label-saldo").text("Saldo: $-");
                        saldo = 0;
                        popupError(null, data.msg);
                        $("#label-saldo").css("color", "#767676");
                    }
                },
                error: function () {
                    hideOverlay();
                    popupError(null, "Hubo un error en la operación");
                }
            });
        }
    }

    function backCliente() {
        $("#IdCliente").val("");
        tmpclient = "";
        $("#label-saldo").text("$0");
        $("#acCliente").val("");
        $("#label-saldo").css("color", "#767676");
        $("#modal-cliente").modal("hide");
    }
</script>

Code/MvcAppDCR/Views/CuentaCorriente/PrintComprobante.cshtml
@model Domine.Dto.DtoPrintOperacionCtaCte
@{
    Layout = null;
}
<html>
<head>
    <style>
        body{
            font-size:small;
        }
        #tablacheques table {
            border: 1px solid;
        }

            #tablacheques table th {
                width: 150px;
                 font-size:small;
            }

            #tablacheques table td {
                width: 150px;
                border: 1px solid;
                font-size:small;
                text-align:center;
            }
    </style>
</head>
<body>
    <div style="float:left;text-align:center;width:20%">        
        <p style="font-size:14px;font-weight:700">@Model.Empresa.Nombre</p>
        <p>@Model.Empresa.Direccion</p>
        <p>C.U.I.T @Model.Empresa.Cuit</p>
    </div>
    <div style="float:right;text-align:center;width:49%">
        <label>Fecha: @DateTime.Now.ToString("dd/MM/yyyy")</label>
    </div>

    <div style="width:100%;text-align:center;float:left">
        <hr />
        <label>Comprobante Original</label>
        <hr />
    </div>
    <div style="width:50%;float:left;">
        <div>
            <label>Nro. Operación: @Model.OperacionCtaCte.IdOperacionCuentaCorriente</label>           
        </div>
    </div>
   <div style="width:100%;float:left">
        <br />
        <p>Cliente: @Model.OperacionCtaCte.CuentaCorriente.Cliente.Nombre</p>
        <p>Domicilio: @Model.OperacionCtaCte.CuentaCorriente.Cliente.Domicilio</p>
        <p>C.U.I.T: @Model.OperacionCtaCte.CuentaCorriente.Cliente.CUIT</p>
    </div>
    <div style="width:100%;float:left">
        <br />
        @if (@Model.OperacionCtaCte.TipoMovimiento == 2)
        {
             <p>En la Ciudad de Mendoza,Rca. Argentina. En el dia de la fecha <b>RECIBI/MOS</b>, la suma de @Model.OperacionCtaCte.Monto.ToString("C2"). (@Model.MontoLetra)</p>
        }
        else
        {
              <p>En la Ciudad de Mendoza,Rca. Argentina. En el dia de la fecha <b>LIQUIDAMOS</b>, la suma de @Model.OperacionCtaCte.Monto.ToString("C2"). (@Model.MontoLetra)</p>
        }
       
    </div>
    <div style="width:100%;float:left">
        <label>Firma:</label>
        <br />
        <br />
        <label>Aclaración:</label>
        <br />
        <br />
        <label>DNI Número:</label>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
    
    @*duplicado*@

     <div style="float:left;text-align:center;width:20%">
        <p style="font-size:14px;font-weight:700">@Model.Empresa.Nombre</p>
        <p>@Model.Empresa.Direccion</p>
        <p>C.U.I.T @Model.Empresa.Cuit</p>
    </div>
    <div style="float:right;text-align:center;width:49%">
        <label>Fecha: @DateTime.Now.ToString("dd/MM/yyyy")</label>
    </div>

    <div style="width:100%;text-align:center;float:left">
        <hr />
        <label>Comprobante Duplicado</label>
        <hr />
    </div>
    <div style="width:50%;float:left;">
        <div>
            <label>Nro. Operación: @Model.OperacionCtaCte.IdOperacionCuentaCorriente</label>           
        </div>
    </div>
    <div style="width:100%;float:left">
        <br />
        <p>Cliente: @Model.OperacionCtaCte.CuentaCorriente.Cliente.Nombre</p>
        <p>Domicilio: @Model.OperacionCtaCte.CuentaCorriente.Cliente.Domicilio</p>
        <p>C.U.I.T: @Model.OperacionCtaCte.CuentaCorriente.Cliente.CUIT</p>
    </div>
    <div style="width:100%;float:left">
        <br />
        @if (@Model.OperacionCtaCte.TipoMovimiento == 2)
        {
             <p>En la Ciudad de Mendoza,Rca. Argentina. En el dia de la fecha <b>RECIBI/MOS</b>, la suma de @Model.OperacionCtaCte.Monto.ToString("C2").</p>
        }
        else
        {
              <p>En la Ciudad de Mendoza,Rca. Argentina. En el dia de la fecha <b>LIQUIDAMOS</b>, la suma de @Model.OperacionCtaCte.Monto.ToString("C2").</p>
        }
       
    </div>
    <div style="width:100%;float:left">
        <br />
        <br />
        <label>Firma:</label>
        <br />
        <br />
        <label>Aclaración:</label>
        <br />
        <br />
        <label>DNI Número:</label>
    </div>
</body>
</html>

Code/MvcAppDCR/Views/CuentaCorriente/Reporte.cshtml
<section class="panel">
    <div class="panel-body">
        <div class="form">
            <div class="panel-body" style="padding: 5px;">
                <div class="@Bootstrap.formgroup">
                    @Html.Label("", Resource.FechaDesde, new { @class = Bootstrap.label })
                    <div class="col-lg-9">
                        <div class="input-group m-bot15">
                            @Html.TextBox("txtFechaDesde", "", new { @id = "txtFechaDesde", @class = Bootstrap.datepicker, @Value = DateTime.Now.AddMonths(-6).ToShortDateString() })
                        </div>
                    </div>
                </div>
                <div class="@Bootstrap.formgroup">
                    @Html.Label("", Resource.FechaHasta, new { @class = Bootstrap.label })
                    <div class="col-lg-9">
                        <div class="input-group m-bot15">
                            @Html.TextBox("txtFechaHasta", "", new { @id = "txtFechaHasta", @class = Bootstrap.datepicker, @Value = DateTime.Now.ToShortDateString() })
                        </div>
                    </div>
                </div>
                <div class="@Bootstrap.formgroup">
                    <div class="col-lg-offset-3 col-lg-6">
                        <button class="btn btn-primary" type="button" onclick="imprimirResumen()" id="btnSave">@Resource.ImprimirResumen</button>
                        <button class="btn btn-danger" type="button" onclick="closePopUp()">@Resource.Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>