Code/MvcAppDCR/Controllers/AccessController.cs
using Business;
using System.Linq;
using CurrentContext;
using Domine;
using MvcAppDCR.Code;
using MvcAppDCR.Model.Security;
using MvcAppDCR.Utils;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;
using Resources;

namespace Controllers
{
    public class AccessController : BaseController
    {
        [HttpGet]
        public ActionResult Error(string errorType, string message, string url = "", string btnGoToLabel = "", bool redirectBtn = true)
        {
            ViewData["ErrorType"] = errorType;
            ViewData["Message"] = message;
            ViewData["redirectBtn"] = redirectBtn;

            if (redirectBtn)
            {
                if (!string.IsNullOrEmpty(url) && !string.IsNullOrEmpty(btnGoToLabel))
                {
                    ViewData["UrlRedirect"] = url;
                    ViewData["BtnGoToLabel"] = btnGoToLabel;
                }
                else
                {
                    ViewData["UrlRedirect"] = Url.Action("Login", "Access");
                    ViewData["BtnGoToLabel"] = "Login";
                }
            }

            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login(string returnUrl = "")
        {
           
               
              if (User.Identity.IsAuthenticated)
            {
                return Logout();
            }

            ViewBag.ReturnUrl = returnUrl;
            ViewBag.Sucursales = new List<SelectListItem>();

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UsuarioLogin model, string returnUrl = "")
        {

            ModelState.Remove("IdEmpresa");

            if (ModelState.IsValid)
            {
                if (CustomMembership.ValidateUser(model.NombreUsuario, model.Contrasenia))
                {
                    FormsAuthentication.SetAuthCookie(model.NombreUsuario, model.RememberMe);

                    var currentUsuario = CustomMembership.GetCurrentUser(model.NombreUsuario);

                    if (currentUsuario != null)
                    {
                        SessionContext.UsuarioActual = (Usuario)currentUsuario.User;
                        //SessionContext.Empresa = SessionContext.UsuarioActual.Empresa;

                        var usuarioSucursal = SucursalUsuarioBusiness.Instance.GetCurrentUsuarioDefaultSucursal();

                        SessionContext.IdSucursalOperacionActual = model.IdSucursal;
                        SessionContext.IdEmpresaActual = model.IdEmpresa;
                        SessionContext.Configuracion = ChequeBusiness.Instance.GetByConditions<Configuracion>(config => config.IdEmpresa == SessionContext.IdEmpresaActual).FirstOrDefault();



                        var perfiles = UsuarioBusiness.Instance.GetUsuarioById(SessionContext.UsuarioActual.IdUsuario);
                        SessionContext.Perfil = (Luma.Utils.Enumeraciones.Perfil.TipoPerfil)perfiles.IdPerfil;
                        //SessionContext.Perfil = (Luma.Utils.Enumeraciones.Perfil.TipoPerfil)perfiles.ToList()[0].IdPerfil;





                        AuditoriaBusiness.Instance.AuditoriaLogin();
                    }

                    return Json(
                        new
                        {
                            msg = "Registro guardado correctamente",
                            status = Constant.SuccessMessages.MESSAGE_OK,
                            url = Url.Action("Index", "Home")
                        });
                }
                else
                {
                    return ExceptionManager.Instance.JsonError("Nombre de usuario o contraseña incorrectas");
                }
            }

            return ExceptionManager.Instance.JsonError(ModelState);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult DirectLogin(long idUsuario, long idEmpresa, string returnUrl = "")
        {
            var usuario = UsuarioBusiness.Instance.GetEntity(idUsuario);

            if (usuario != null)
            {
                FormsAuthentication.SetAuthCookie(usuario.NombreUsuario, false);

                var currentUsuario = CustomMembership.GetCurrentUser(usuario.NombreUsuario);

                if (currentUsuario != null)
                {
                    SessionContext.UsuarioActual = (Usuario)currentUsuario.User;
                    
                    AuditoriaBusiness.Instance.AuditoriaLogin();
                }

                return Redirect(returnUrl);
            }

            return HttpNotFound();
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [AllowAnonymous]
        public ActionResult Logout()
        {
            if (CustomMembership.GetCurrentUser() != null)
            {
                AuditoriaBusiness.Instance.AuditoriaLogout();

                SessionContext.UsuarioActual = null;
            }

            FormsAuthentication.SignOut();

            return Redirect(FormsAuthentication.LoginUrl);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public JsonResult ResetPassword(Usuario model)
        {
            try
            {
                ModelState.Remove("Nombre");
                ModelState.Remove("Apellido");
                ModelState.Remove("NombreUsuario");
                ModelState.Remove("Contrasenia");
                ModelState.Remove("IdEmpresa");

                if (ModelState.IsValid)
                {
                    UsuarioBusiness.Instance.RestablecerContrasenia(model.Email);

                    return Json(
                        new
                        {
                            msg = "Registro guardado correctamente",
                            status = Constant.SuccessMessages.MESSAGE_OK
                        });
                }
                else
                {
                    return ExceptionManager.Instance.JsonError("Debe ingresar un e-mail válido", Constant.SuccessMessages.ERROR_VAR_MODAL);
                }
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex, Constant.SuccessMessages.ERROR_VAR_MODAL);
            }
        }
              
          [HttpPost]
        public JsonResult ChangeCurrentSucursal(long? idSucursal)
		{
			try
			{
				if (idSucursal.HasValue && idSucursal.Value > 0)
				{
                    if (SucursalUsuarioBusiness.Instance.HasUsuarioSucursalAssigned(idSucursal.Value))
					{						
                        SessionContext.IdSucursalOperacionActual = idSucursal;

						return Json(new { status = Constant.SuccessMessages.MESSAGE_OK });
					}
					else
					{
						return ExceptionManager.Instance.JsonError(Resource.CannotChangeToSucursalOperacion);
					}
				}
				else
				{
					return ExceptionManager.Instance.JsonError(Resource.ServerConnectionError);
				}
			}
			catch (System.Exception ex)
			{
				return ExceptionManager.Instance.JsonError(ex);
			}
		}
    }
}

Code/MvcAppDCR/Controllers/EmpresaController.cs
using Business;
using Domine;
using MvcAppDCR.Code;
using MvcAppDCR.Utils;
using System;
using System.Web.Mvc;

namespace Controllers
{
    public class EmpresaController : BaseController
    {
        [HttpPost]
        [AllowAnonymous]
        public JsonResult GetEmpresasByNombreUsuarioOrderById(string nombreUsuario = "")
        {
            try
            {
                var empresas = EmpresaBusiness.Instance.GetEmpresasByNombreUsuario(nombreUsuario);

                var options = WebHelper.GetSelectListItem(empresas, "Id", "Nombre");

                return Json(new { status = Constant.SuccessMessages.MESSAGE_OK, Options = options });
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }
    }
}

Code/MvcAppDCR/Controllers/SucursalController.cs
using Business;
using Controllers;
using Domine;
using MvcAppDCR.Code;
using MvcAppDCR.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Controllers
{
    public class SucursalController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetSucursales(string numero = "", [Bind(Prefix = "$top")]int top = 10, [Bind(Prefix = "$skip")]int skip = 0)
        {
            try
            {
                int rowCount = 0;

                var list = SucursalBusiness.Instance.GetByFilters(numero, skip, top, ref rowCount);

                return this.JsonSerialize(new { status = Constant.SuccessMessages.MESSAGE_OK, result = list, count = rowCount }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { result = new { }, count = 0, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult ABMSucursal(long? id)
        {
            var empresas = EmpresaBusiness.Instance.GetAllEmpresas();

            ViewBag.Empresas = WebHelper.GetSelectListItem(empresas, "Id", "Nombre");

            if (!id.HasValue || id.Value <= 0)
            {
                return View(new Sucursal());
            }

            var entity = SucursalBusiness.Instance.GetEntity(id.Value);

            if (entity == null)
            {
                return HttpNotFound();
            }

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ABMSucursal(Sucursal sucursal)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    SucursalBusiness.Instance.SaveOrUpdateSucursal(sucursal);

                    return Json(
                        new
                        {
                            msg = "Registro guardado correctamente",
                            status = Constant.SuccessMessages.MESSAGE_OK,
                            url = Url.Action("Index")
                        });
                }
                else
                {
                    return ExceptionManager.Instance.JsonError(ModelState);
                }
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            try
            {
                SucursalBusiness.Instance.DeleteLogic(id, SucursalBusiness.Instance.ValidateDelete, AuditoriaBusiness.Instance.AuditoriaSucursal);

                return Json(new { status = Constant.SuccessMessages.MESSAGE_OK });
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }

        [HttpPost]
        public JsonResult ValidateSucursal(string numero = "")
        {
            try
            {
                if (!string.IsNullOrEmpty(numero))
                {
                    var entity = SucursalBusiness.Instance.SucursalExist(numero);

                    if (entity != null)
                    {
                        return Json(new { status = Constant.SuccessMessages.MESSAGE_OK, Exist = true, Id = entity.IdSucursal });
                    }
                    else
                    {
                        return Json(new { status = Constant.SuccessMessages.MESSAGE_OK, Exist = false });
                    }
                }
                else
                {
                    return ExceptionManager.Instance.JsonError("Requerido");
                }
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult GetSucursalesByNombreUsuarioOrderById(string nombreUsuario = "")
      {
            try
            {
                var sucursales = SucursalBusiness.Instance.GetSucursalByNombreUsuario(nombreUsuario);

                var empresa = EmpresaBusiness.Instance.GetEmpresasByNombreUsuario(nombreUsuario).FirstOrDefault();

                var options = WebHelper.GetSelectListItem(sucursales, "IdSucursal", "Descripcion");

                return Json(new { status = Constant.SuccessMessages.MESSAGE_OK, Options = options, Empresa = empresa.Id});
            }
            catch (Exception ex)
            {
                return ExceptionManager.Instance.JsonError(ex);
            }
        }
        
    }
}

Code/MvcAppDCR/Views/Access/Login.cshtml
@model MvcAppDCR.Model.Security.UsuarioLogin

@{
    Layout = null;
    ViewBag.Title = "Ingreso al sistema";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="descripcion" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="images/favicon.html">

    <title>@ViewBag.Title</title>

    @Styles.Render(MvcAppDCR.Code.Constant.Bundle.CSS_BootstrapAll)
    @Styles.Render(MvcAppDCR.Code.Constant.Bundle.CSS_Template)
	
    <script type="text/javascript" id="globalVars">
        var msgoverlay = "Espere por favor...";
    </script>
</head>
<body class="login-body">
    <div class="container">
        @using (Ajax.BeginForm("Login", "Access", null, new AjaxOptions
        {
            HttpMethod = "Post",
            InsertionMode = InsertionMode.Replace,
            OnBegin = MvcAppDCR.Code.Constant.Ajax.JsOnBeginAjax,
            OnSuccess = MvcAppDCR.Code.Constant.Ajax.JsOnSuccessAjax
        },
		new { @class = "form-signin", id = "form-signin", autocomplete = "off" }))
        {
            @Html.AntiForgeryToken()
            <div id="head">
                <h2 class="form-signin-heading">
                    <img src="~/Content/Images/logo.jpg" style="width:175px" />
                </h2>
            </div>
            <div class="login-wrap">
                <div class="usuario-login-info"> 
                    @Html.TextBoxFor(model => model.NombreUsuario, new { @class = Luma.Utils.HtmlCSSConst.Bootstrap.input , placeholder = Resource.NombreUsuario})
                    @Html.PasswordFor(model => model.Contrasenia, new { @class = Luma.Utils.HtmlCSSConst.Bootstrap.input, placeholder = "Contraseña" })
                    @*@Html.DropDownListFor(model => model.IdSucursal, (List<SelectListItem>)ViewBag.Sucursales, new { @class = Bootstrap.input, Resource.Sucursal })*@
                    @Html.HiddenFor(model => model.IdEmpresa)
                    <div class="@Luma.Utils.HtmlCSSConst.Bootstrap.formgroup">
                        @Html.ValidationMessage(MvcAppDCR.Code.Constant.SuccessMessages.ERROR_VAR)
                    </div>
                </div>
                <div class="login-info-button">
                    <label class="checkbox">
                        <span class="pull-right">
                            <a data-toggle="modal" href="#changeContraseniaModal">
								¿Perdio su clave?
                            </a>
                        </span>
                    </label>
                </div>
				<div class="@Luma.Utils.HtmlCSSConst.Bootstrap.formgroup">
					<b>
						<label class="error-label" id="@MvcAppDCR.Code.Constant.SuccessMessages.ERROR_VAR"></label>
					</b>
				</div>
                <button class="btn btn-lg btn-login btn-block" type="submit" id="btnLogin">
					Ingresar
                </button>
            </div>
        }
    </div>
	<div id="loginInfo"
		data-get-empresas-url="@Url.Action("GetEmpresasByNombreUsuarioOrderById", "Empresa")"
        data-get-sucursales-url="@Url.Action("GetSucursalesByNombreUsuarioOrderById", "Sucursal")"
		data-no-sucursales-asigandas-texto="@Resource.NoSucursalesAsignadas"
		data-error-text="Mensaje de error">
	</div>
	<div id="masterInfo"
		data-content-url="@Url.Content("~/Content/")"
		data-accept="@Html.Raw("Aceptar")">
	</div>	
    <!-- Reser pssword modal -->
	@using (Ajax.BeginForm("ResetPassword", null, new AjaxOptions
	{
		HttpMethod = "Post",
		InsertionMode = InsertionMode.Replace,
		OnBegin = MvcAppDCR.Code.Constant.Ajax.JsOnBeginAjax,
		OnSuccess = "onRestablecerContraseniaSuccessAjax(data, status, xhr);"
	},
	new { @class = "cmxform form-horizontal", id = "form-reset-password", autocomplete = "off" }))
	{
		@Html.AntiForgeryToken()
		<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="changeContraseniaModal" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
							&times;
						</button>
						<h4 class="modal-title">
							¿Perdio su clave?
						</h4>
					</div>
					<div class="modal-body">
						<p>Ingrese su e-mail para restablecer su contraseña</p>
						<input type="text" name="email" placeholder="E-mail" autocomplete="off" class="form-control placeholder-no-fix">
						<div>
							<b>
								<label class="error-label" id="@MvcAppDCR.Code.Constant.SuccessMessages.ERROR_VAR_MODAL"></label>
							</b>
						</div>
					</div>
					<div class="modal-footer">
						<button data-dismiss="modal" class="btn btn-default" type="button">
							Cancelar
						</button>
						<button class="btn btn-success" type="submit">
							Enviar
						</button>
					</div>
				</div>
			</div>
		</div>
	}
    <!-- modal -->

    @Scripts.Render(MvcAppDCR.Code.Constant.Bundle.Script_JQueryAll)
    @Scripts.Render(MvcAppDCR.Code.Constant.Bundle.Script_Bootstrap)
	
	<script type="text/javascript" src="@Url.Content("~/Scripts/Site/Login/login.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/Scripts/Site/site.js")"></script>
</body>
</html>

Code/MvcAppDCR/Views/Access/ResetPassword.cshtml
@{
	Layout = null;
	ViewBag.Title = Reestablecer Contraseña;
}

<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
	
    <meta name="viewport" content="width=device-width" />

    @Styles.Render(Constant.Bundle.CSS_BootstrapAll)
    @Styles.Render(Constant.Bundle.CSS_Template)

    @Scripts.Render(Constant.Bundle.Script_JQueryAll)
    @Scripts.Render(Constant.Bundle.Script_Bootstrap)
    @Scripts.Render(Constant.Bundle.Script_TemplateAll)
    @Scripts.Render(Constant.Bundle.Script_Site)
	
	<script type="text/javascript" src="@Url.Content("~/Scripts/Site/Login/login.js")"></script>
</head>
<body>
	<div class="container">
		<form role="form" class="form-signin">
			<h2 class="form-signin-heading">Restablecer contraseña</h2>
			@Html.TextBox("txtEmail", "", new
											{
												@id = "txtEmail",
												@class = "form-control email required",
												@maxlength = "150",
												@type = "email",
												@onkeyup = "EnterPressed(event);",
												@placeholder = "E-mail",
												@autofocus = ""
											})
			<br />
			<button type="button" class="btn btn-lg btn-primary btn-block" onclick="ResetContrasenia();">
				Enviar
			</button>
		</form>
    </div>
	<div id="resetContraseniaInfo"
		data-send-url="@Url.Action("SendResetPassworEmail", "Access")"
		data-access-url="@Url.Action("SendResetPassworEmail", "Access")"
		data-error-tipo="@Html.Raw("Restablecimiento de contraseña")"
		data-message="@Html.Raw("La nueva contraseña ha sido enviada al e-mail")"
		data-required="@Html.Raw("Debe completar los campos requeridos")">
	</div>
</body>
</html>